In [2]:
import pandas as pd
import numpy as np

In [71]:
# •Load the file students.csv and make sure Score Date is parsed as datetime.

df = pd.read_excel('students.xlsx', parse_dates= ['Score Date'])
df

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6     Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [4]:
# •Print the shape, columns list, and data types of the DataFrame.
print(f'Shape:\n{df.shape}\n')

print(f'Columns List:\n{df.columns}\n')

print(f'Data Types:\n{df.dtypes}\n')

Shape:
(9, 8)

Columns List:
Index(['Student ID', 'Name', 'Age', 'Grade', 'Subject', 'City', 'Passed',
       'Score Date'],
      dtype='object')

Data Types:
Student ID             int64
Name                  object
Age                    int64
Grade                float64
Subject               object
City                  object
Passed                  bool
Score Date    datetime64[ns]
dtype: object

In [5]:
# •Show the first 7 rows and the last 3 rows. 
print(f'first 7 rows:\n{df.head(7)}\n')

print(f'last 3 rows:\n{df.tail(3)}\n')

first 7 rows:
   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2    Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3    Omar   19   65.0       Math        Giza   False 2025-01-20
3           4    Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5  Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6    Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7    Yara   30   89.0       Math       Cairo    True        NaT

last 3 rows:
   Student ID     Name  Age  Grade    Subject   City  Passed Score Date
6           7     Yara   30   89.0       Math  Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12

In [6]:
# •Show how many missing values in each column.
print(df.isna().sum())

Student ID    0
Name          0
Age           0
Grade         1
Subject       0
City          0
Passed        0
Score Date    1
dtype: int64

In [7]:
# •What is the average, minimum, and maximum Grade?

print(f"min grade:\n{ df['Grade'].min() }\n")
print(f"avg grade:\n{ df['Grade'].mean() }\n")
print(f"max grade:\n{ df['Grade'].max() }\n")

# Or using agg() Function
print(f"{df['Grade'].agg(['min', 'mean', 'max'])}")

min grade:
55.0

avg grade:
76.375

max grade:
92.0

min     55.000
mean    76.375
max     92.000
Name: Grade, dtype: float64

In [17]:

# •How many unique cities are there? List them.
print(f"Count: {df['City'].nunique()}\n")
print(f"Names: {df['City'].unique()}\n")

Count: 4

Names: ['Cairo' 'Alexandria' 'Giza' 'Mansoura']

In [20]:
# •Use value_counts() to show how many students per Subject
print(f"Students per subject:\n{df['Subject'].value_counts()}")

Students per subject:
Subject
Math         3
Chemistry    3
Physics      2
English      1
Name: count, dtype: int64

In [21]:
# •Select only the columns: Name, Grade, Subject, City.
df[['Name', 'Grade', 'Subject', 'City']]

      Name  Grade    Subject        City
0    Ahmed   88.0       Math       Cairo
1     Sara   92.0    Physics  Alexandria
2     Omar   65.0       Math        Giza
3     Lina   78.0  Chemistry       Cairo
4   Khaled   55.0    Physics    Mansoura
5     Nour    NaN    English  Alexandria
6     Yara   89.0       Math       Cairo
7  Mohamed   72.0  Chemistry        Giza
8  Mohamed   72.0  Chemistry        Giza

In [26]:
# •Show all students who Passed and have Grade ≥ 85.
df[(df['Passed'] == True) & (df['Grade'] >= 85)]

   Student ID   Name  Age  Grade  Subject        City  Passed Score Date
0           1  Ahmed   25   88.0     Math       Cairo    True 2025-01-15
1           2   Sara   32   92.0  Physics  Alexandria    True 2025-02-10
6           7   Yara   30   89.0     Math       Cairo    True        NaT

In [38]:
# •Show students whose Name contains the letter "a" or "A" (case insensitive).

df[df['Name'].str.contains('a', case= False, na= False)]
# Or 

# df[df['Name'].str.contains('a', case= False, na= False)]['Name']

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [ ]:
# •Show students in Cairo or Alexandria with Grade < 80.
df[ ( df['City'].isin(['Cairo', 'Alexandria']) ) & ( df['Grade'] < 80 ) ]

   Student ID  Name  Age  Grade    Subject   City  Passed Score Date
3           4  Lina   28   78.0  Chemistry  Cairo    True 2025-03-05

In [43]:
# •Show students with Grade between 80 and 90 (inclusive).
df[df['Grade'].between(80, 90)]

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True 2025-01-15
6           7   Yara   30   89.0    Math  Cairo    True        NaT

In [47]:
# •Using .loc, change Khaled's grade from 55 to 68.
print(df[df['Name'] == 'Khaled'])

df.loc[df['Name'] == 'Khaled', 'Grade'] = 80

df[df['Name'] == 'Khaled']

   Student ID    Name  Age  Grade  Subject      City  Passed Score Date
4           5  Khaled   45   55.0  Physics  Mansoura   False 2025-02-28

   Student ID    Name  Age  Grade  Subject      City  Passed Score Date
4           5  Khaled   45   80.0  Physics  Mansoura   False 2025-02-28

In [48]:
# •Add a new column Is_Excellent that is True if Grade ≥ 90, False otherwise (vectorized).
df['Is_Excellent'] = df['Grade'] >= 90

df[['Grade', 'Is_Excellent']]

   Grade  Is_Excellent
0   88.0         False
1   92.0          True
2   65.0         False
3   78.0         False
4   80.0         False
5    NaN         False
6   89.0         False
7   72.0         False
8   72.0         False

In [50]:
# •Fill missing Grade values with the average Grade.
print(df['Grade'])

print(df['Grade'].fillna(df['Grade'].mean()))

0    88.0
1    92.0
2    65.0
3    78.0
4    80.0
5     NaN
6    89.0
7    72.0
8    72.0
Name: Grade, dtype: float64
0    88.0
1    92.0
2    65.0
3    78.0
4    80.0
5    79.5
6    89.0
7    72.0
8    72.0
Name: Grade, dtype: float64

`.mode()` method in pandas returns a Series, not a single value. 
Even if there is only one most frequent date, pandas provides it as a list-like object, which `fillna()` doesn't know how to map to a single missing cell.
So, to select the first element of that Series I should use [0].

In [57]:
# •Fill missing Score Date values with the most common date (mode).
print(df['Score Date'])

print(df['Score Date'].fillna( df['Score Date'].mode()[0] ) )

0   2025-01-15
1   2025-02-10
2   2025-01-20
3   2025-03-05
4   2025-02-28
5   2025-01-10
6          NaT
7   2025-03-12
8   2025-03-12
Name: Score Date, dtype: datetime64[ns]
0   2025-01-15
1   2025-02-10
2   2025-01-20
3   2025-03-05
4   2025-02-28
5   2025-01-10
6   2025-03-12
7   2025-03-12
8   2025-03-12
Name: Score Date, dtype: datetime64[ns]

In [58]:
# •Add a new column Final_Grade = Grade + 5 (bonus points).
df['Final_Grade'] = df['Grade'] + 5

df[['Grade', 'Final_Grade']]

   Grade  Final_Grade
0   88.0         93.0
1   92.0         97.0
2   65.0         70.0
3   78.0         83.0
4   80.0         85.0
5    NaN          NaN
6   89.0         94.0
7   72.0         77.0
8   72.0         77.0

In [60]:
# •Create a column Grade_Category using pd.cut with bins:
# •0–69 → "Fail"
# •70–79 → "Average"
# •80–89 → "Good"
# •90–100 → "Excellent"

df['Grade_Category'] = pd.cut(
    df['Grade'], 
    bins= [0, 69, 79, 89, 100], 
    labels = ['Fail', 'Average', 'Good', 'Excellent'], 
    include_lowest= True
)

df[['Grade', 'Grade_Category']]

   Grade Grade_Category
0   88.0           Good
1   92.0      Excellent
2   65.0           Fail
3   78.0        Average
4   80.0           Good
5    NaN            NaN
6   89.0           Good
7   72.0        Average
8   72.0        Average

In [66]:
# •Remove the column Student ID.
# print(df)
df.drop(columns= 'Student ID')

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
2,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
4,Khaled,45,80.0,Physics,Mansoura,False,2025-02-28,False,85.0,Good
5,Nour,22,NaN,English,Alexandria,True,2025-01-10,False,NaN,NaN
6,Yara,30,89.0,Math,Cairo,True,NaT,False,94.0,Good
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [67]:
# •Keep only students who Passed.
df2 = df[df['Passed'] == True]
df2

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
5,6,Nour,22,NaN,English,Alexandria,True,2025-01-10,False,NaN,NaN
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False,94.0,Good
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [68]:
# •Sort the DataFrame by Grade descending.
df.sort_values('Grade', ascending=False)

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False,94.0,Good
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
4,5,Khaled,45,80.0,Physics,Mansoura,False,2025-02-28,False,85.0,Good
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
5,6,Nour,22,NaN,English,Alexandria,True,2025-01-10,False,NaN,NaN

In [70]:
# •Sort by City ascending, then inside each city sort by Grade descending.

df.sort_values(['City', 'Grade'], ascending= [True, False])

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
5,6,Nour,22,NaN,English,Alexandria,True,2025-01-10,False,NaN,NaN
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False,94.0,Good
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
4,5,Khaled,45,80.0,Physics,Mansoura,False,2025-02-28,False,85.0,Good

In [81]:
# •Add a column Rank that ranks students by Grade (1 = highest, handle ties with 'min').

# df['rank_min'] = df['Grade'].rank(ascending=False, method= 'min')
df['rank min'] = df['Grade'].rank(ascending=False, method= 'min')
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,rank min
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,3.0
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,1.0
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,7.0
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,4.0
4,5,Khaled,45,55.0,Physics,Mansoura,False,2025-02-28,8.0
5,6,Nour,22,NaN,English,Alexandria,True,2025-01-10,NaN
6,7,Yara,30,89.0,Math,Cairo,True,NaT,2.0
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,5.0
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,5.0

In [ ]:
# •Show the top 4 students with the highest grades (use nlargest).
df['Grade'].nlargest(4)

# or
df.nlargest(4, 'Grade')

   Student ID   Name  Age  Grade    Subject        City  Passed Score Date
1           2   Sara   32   92.0    Physics  Alexandria    True 2025-02-10
6           7   Yara   30   89.0       Math       Cairo    True        NaT
0           1  Ahmed   25   88.0       Math       Cairo    True 2025-01-15
3           4   Lina   28   78.0  Chemistry       Cairo    True 2025-03-05

In [82]:
# •Show the 3 youngest students (use nsmallest on Age).

df.nsmallest(3, 'Age')

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,rank min
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,7.0
5,6,Nour,22,NaN,English,Alexandria,True,2025-01-10,NaN
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,3.0

#### •Find the student(s) with the highest Grade and show their Name and Grade.
##### This is explanation and clarification for me to remember, NOT CHEATING.

**1. Using `nlargest()`** 

Is often the most readable method for getting the "top" items. It is specifically designed to return the top `n` rows.

with option/parameter `keep="all"` ensures that if there is a tie for first place, both/all students are returned.

---
**2. Using `rank()`**

`rank()` assigns a numerical rank to every student. I can then filter by `rank == 1`.

---
### Which one should we choose?

| Method | Best For... |
| --- | --- |
| **Boolean Filtering** (`df['Grade'] == max()`) | Simple, direct, and very fast for single conditions. |
| **`nlargest()`** | Getting the top $N$ results (e.g., "Top 3 students") while handling ties easily. |
| **`rank()`** | Complex scenarios where you need to know the relative position of everyone in the class. |

In [ ]:
# •Find the student(s) with the highest Grade and show their Name and Grade.Lab
# using ---------------> boolean condition
# df[ condition ] [ list of wanted columns ]
df[ df['Grade'] == df['Grade'].max() ] [['Name', 'Grade']]

# or using .loc()
df.loc[df['Grade'] == df['Grade'].max(), ['Name', 'Grade']]


# or using ------------> .nlargest() <------------                  
# 'keep="all"' ensures that if there is a tie for first place, both/all students are returned.
top_students= df.nlargest(1, 'Grade', keep='all')[['Name', 'Grade']]
top_students

# or using ------------> .rank() <------------                  
# 'min' method ensures that tied students get the same top rank
# Filter for the students ranked 1

df['Rank'] = df['Grade'].rank(method='min', ascending=False)

top_students = df[df['Rank'] == 1][['Name', 'Grade']]
top_students

   Name  Grade
1  Sara   92.0

In [127]:
# •After filling missing grades, recalculate the average Grade per Subject.

df['Grade'] = df['Grade'].fillna(df['Grade'].mean())

avg_per_subject = df.groupby('Subject')['Grade'].mean()

avg_per_subject

Subject
Chemistry    74.000000
English       0.000000
Math         80.666667
Physics      73.500000
Name: Grade, dtype: float64

In [124]:
# •Create a new column City_Avg that shows the average grade of each student's city (using transform).
# transform() performs the calculation for each group and broadcasts the result back to the original index size, 
# allowing you to easily assign it as a new column.
df['City_Avg'] = df.groupby('City')['Grade'].transform('mean')

df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,rank min,Rank,City_Avg
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,3.0,3.0,85.000000
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,1.0,1.0,46.000000
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,7.0,7.0,69.666667
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,4.0,4.0,85.000000
4,5,Khaled,45,55.0,Physics,Mansoura,False,2025-02-28,8.0,8.0,55.000000
5,6,Nour,22,0.0,English,Alexandria,True,2025-01-10,NaN,NaN,46.000000
6,7,Yara,30,89.0,Math,Cairo,True,NaT,2.0,2.0,85.000000
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,5.0,5.0,69.666667
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,5.0,5.0,69.666667

In [129]:
# •Show the subject with the highest average grade
print(avg_per_subject)
avg_per_subject.idxmax()

Subject
Chemistry    74.000000
English       0.000000
Math         80.666667
Physics      73.500000
Name: Grade, dtype: float64

'Math'